apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: ns1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: yossefsameh/final-jenkins1
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_home
          - name: kubernetes
            mountPath: /usr/bin/kubectl
            subPath: kubectl
            
          - name: docker
            mountPath: /usr/bin/docker
            subPath: docker
            
          - name: dockersock
            mountPath: /var/run/docker.sock
      initContainers:
        - name: init-docker
          image: docker
          command: ["cp","/usr/local/bin/docker", "/opt/othertemp"]    
            
          volumeMounts:  
            - name: docker
              mountPath: /opt/othertemp
 
        - name: init-k8s
          image: alpine/k8s:1.23.13
          command: ["cp","/usr/bin/kubectl", "/opt/temp"]

          volumeMounts:
            - name: kubernetes
              mountPath: "/opt/temp"
      volumes:
        - name: jenkins-vol
          emptyDir: {}
        - name: docker
          emptyDir: {} 
        - name: kubernetes
          emptyDir: {}
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock

          
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: ns1
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins
